services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      JWT_SECRET: secretKey
      EMAIL_USER: your-email@example.com
      EMAIL_PASS: your-email-password
      SMTP_HOST: smtp.example.com
      SMTP_PORT: 587
    volumes:
      - .:/app
    command: npm run start:prod

  test:
    build: .
    environment:
      JWT_SECRET: secretKey
      EMAIL_USER: your-email@example.com
      EMAIL_PASS: your-email-password
      SMTP_HOST: smtp.example.com
      SMTP_PORT: 587
    volumes:
      - .:/app
    command: sh test-runner.sh
